theme: jekyll-theme-minimal
title: T4D4 Team Website
description: A website for the T4D4 team, explaining FED rate impact.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: About
    url: other_page
